### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ha0ye** [Open-Data-Science-at-SIO/RRROBOTS#2]
## Vision (Long-Term Goal) 

**Develop Materials and Demonstration of Reproducible Research**

Many scientists would like to adopt better habits for reproducible research. Here, our focus is on developing some lessons in doing that for scientific computing, and then teaching those lessons in a graduate-level course where students will reproduce results from existing publications.

The lesson materials and reproductions will be hosted in this Github repo so that others may re-use as appropriate for other courses and workshops.

## Stage 1 (planning, before quarter starts)
- [ ] Develop project roadmap (this document)
- [x] Decide on lesson materials and create schedule of lessons for quarter
- [x] Identify course participants and potential projects

## Stage 2 (during quarter - tied to schedule)
- [x] Organize student groups and assign papers
- [x] Discuss course objectives and logistics
- [x] Basics of using Git and GitHub
- [x] Project and file organization (using GitHub)
- [x] What does reproducibility mean?
- [x] Data Mmanagement and Tidydata principles
- [x] Markdown and GitHub Issue Tracking
- [x] Literate programming and documentation
- [ ] Data validation and unit testing
- [ ] Data and code archiving
- [ ] Licenses and preprints
- [ ] Open Science Framework

## Stage 3 (after quarter ends)
- [ ] Collect feedback from students.
- [ ] Gather reproductions.
- [ ] Discuss outcomes, research ideas, lessons learned.
- [ ] Create GitHub Issues for work to be done 
  * see: #14, #5,
